const $ = id => document.getElementById(id);
let state, selectedId, tab='step', markerMode=false, lastMarker=null, updateChain=Promise.resolve(), undoState=null, toastTimer;
async function api(action,data) {const r=await window.stepfolio.call(action,data);if(!r.ok)throw new Error(r.error);return r.value;}
function toast(message,error=false,undo=false){$('toast-message').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;$('undo').hidden=!undo;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('toast').hidden=true;},error?12000:5000);}
function safe(fn){return async(...args)=>{try{await fn(...args);}catch(e){toast(e.message,true);}};}
function queueUpdate(){const snapshot=structuredClone(state.project);state.dirty=true;updateChain=updateChain.then(()=>api('update',snapshot)).catch(e=>toast(e.message,true));$('save-state').textContent='แก้ไขแล้ว · กู้คืนอัตโนมัติ';}
function current(){return state.project.steps.find(s=>s.id===selectedId);}
function markerSVG(s,n){if(!s.marker)return '';const {width:w,height:h}=s,x=s.marker.x*w,y=s.marker.y*h,r=Math.max(12,Math.min(w,h)*.025),dx=x>w*.65?-1:1,dy=y>h*.65?-1:1,tx=x+dx*r*3.8,ty=y+dy*r*3.8,ex=x+dx*r*.95,ey=y+dy*r*.95;return `<svg class="marker" viewBox="0 0 ${w} ${h}" aria-hidden="true"><circle cx="${x}" cy="${y}" r="${r}" fill="#ff583533" stroke="white" stroke-width="${r*.32}"/><circle cx="${x}" cy="${y}" r="${r}" fill="none" stroke="#f04c2e" stroke-width="${r*.16}"/><path d="M${tx} ${ty} L${ex} ${ey}" stroke="white" stroke-width="${r*.48}"/><path d="M${tx} ${ty} L${ex} ${ey}" stroke="#f04c2e" stroke-width="${r*.25}"/><path d="M${ex+dx*r*1.3} ${ey} L${ex} ${ey} L${ex} ${ey+dy*r*1.3}" fill="none" stroke="#f04c2e" stroke-width="${r*.25}"/><circle cx="${tx}" cy="${ty}" r="${r*.86}" fill="#f04c2e" stroke="white" stroke-width="${r*.15}"/><text x="${tx}" y="${ty+r*.3}" font-family="Arial" font-size="${r*.9}" font-weight="bold" text-anchor="middle" fill="white">${n}</text></svg>`;}
function renderList(){const list=$('step-list');list.replaceChildren();$('count').textContent=state.project.steps.length;if(!state.project.steps.length){list.innerHTML='<div class="list-empty"><span>▧</span>ยังไม่มีขั้นตอน<br>ภาพจากการสาธิตจะปรากฏที่นี่</div>';return;}state.project.steps.forEach((s,i)=>{const b=document.createElement('button');b.className='step-card'+(s.id===selectedId?' selected':'');b.setAttribute('aria-label',`ขั้นตอนที่ ${i+1} ${s.title}`);const num=document.createElement('span');num.className='step-num';num.textContent=String(i+1).padStart(2,'0');const img=document.createElement('img');img.className='step-thumb';img.src=s.image;img.alt='';const meta=document.createElement('div');meta.className='step-meta';const title=document.createElement('strong');title.textContent=s.title||`ขั้นตอนที่ ${i+1}`;const sub=document.createElement('small');sub.textContent=s.description?'มีคำอธิบายแล้ว':'เพิ่มคำอธิบาย';meta.append(title,sub);b.append(num,img,meta);b.onclick=()=>{selectedId=s.id;tab='step';markerMode=false;lastMarker=null;render();};list.append(b);});}
function render(){if(!state)return;if(!current())selectedId=state.project.steps[0]?.id;renderList();const s=current();$('tab-step').classList.toggle('active',tab==='step');$('tab-project').classList.toggle('active',tab==='project');$('empty').hidden=tab!=='step'||!!s;$('step-editor').hidden=tab!=='step'||!s;$('project-editor').hidden=tab!=='project';$('export').disabled=!state.project.steps.length||state.recording;$('record').disabled=state.recording||state.starting||state.stopping;$('save-state').textContent=state.dirty?'แก้ไขแล้ว · กู้คืนอัตโนมัติ':state.currentFile?'บันทึกโครงการแล้ว':'พร้อมเริ่มโครงการใหม่';$('step-position').textContent=s?`ขั้นตอน ${state.project.steps.indexOf(s)+1} จาก ${state.project.steps.length}`:'เริ่มสร้างคู่มือแรกของคุณ';document.title=(state.dirty?'● ':'')+state.project.title+' — Stepfolio';for(const key of ['title','description','author'])$('project-'+key).value=state.project[key];if(s){$('step-title').value=s.title;$('step-description').value=s.description;$('event-label').textContent=s.event;$('step-image').src=s.image;renderMarker();$('move-up').disabled=state.project.steps.indexOf(s)===0;$('move-down').disabled=state.project.steps.indexOf(s)===state.project.steps.length-1;}}
function renderMarker(){const s=current();if(!s)return;$('marker-layer').innerHTML=markerSVG(s,state.project.steps.indexOf(s)+1);$('marker-toggle').textContent=s.marker?'ซ่อนจุดเน้น':'แสดงจุดเน้น';$('image-wrap').classList.toggle('marking',markerMode);$('marker-hint').hidden=!markerMode;$('marker-mode').classList.toggle('primary',markerMode);}
for(const key of ['title','description'])$('step-'+key).oninput=()=>{const s=current();if(!s)return;s[key]=$('step-'+key).value;queueUpdate();renderList();};
for(const key of ['title','description','author'])$('project-'+key).oninput=()=>{state.project[key]=$('project-'+key).value;queueUpdate();};
$('tab-step').onclick=()=>{tab='step';render();};$('tab-project').onclick=()=>{tab='project';render();};
for(const action of ['open','new','recover'])$(action).onclick=safe(async()=>{await updateChain;await api(action);if(action==='recover')$('recovery').hidden=true;});
$('dismiss-recovery').onclick=()=>{$('recovery').hidden=true;};
$('save').onclick=safe(async()=>{await updateChain;if(await api('save',false))toast('บันทึกไฟล์โครงการเรียบร้อย');});
$('save-as').onclick=safe(async()=>{await updateChain;if(await api('save',true))toast('บันทึกสำเนาโครงการเรียบร้อย');});
$('export').onclick=safe(async()=>{await updateChain;$('export').disabled=true;$('export').textContent='กำลังสร้าง PDF…';try{if(await api('export'))toast('ส่งออก PDF เรียบร้อยแล้ว');}finally{$('export').textContent='ส่งออก PDF ↗';$('export').disabled=false;}});
async function permissions(){const p=await api('permissions');const box=$('permissions');box.replaceChildren();if(state.platform!=='darwin'){box.textContent='พร้อมบันทึก · ไม่เก็บข้อความที่พิมพ์';return;}for(const [key,label]of [['screen','การบันทึกหน้าจอ'],['access','Accessibility']]){const row=document.createElement('div');row.className='permission-row';const text=document.createElement('span');text.textContent=(p[key]?'✓ ':'○ ')+label;row.append(text);if(!p[key]){const b=document.createElement('button');b.className='text-button';b.textContent='เปิดการตั้งค่า ↗';b.onclick=safe(()=>api('settings',key));row.append(b);}box.append(row);}const note=document.createElement('small');note.textContent='หลังอนุญาตสิทธิ์ อาจต้องปิดแล้วเปิดโปรแกรมใหม่';box.append(note);}
async function showRecorder(){await updateChain;const displays=await api('displays');$('display').replaceChildren();displays.forEach(d=>{const o=document.createElement('option');o.value=d.id;o.textContent=d.label;$('display').append(o);});await permissions();$('record-dialog').showModal();}
$('record').onclick=safe(showRecorder);$('start-empty').onclick=safe(showRecorder);
window.addEventListener('focus',()=>{if($('record-dialog').open)permissions().catch(()=>{});});
$('start').onclick=safe(async()=>{$('start').disabled=true;$('start').textContent='กำลังเตรียมบันทึก…';try{await api('start',{displayId:$('display').value,scroll:$('capture-scroll').checked,keys:$('capture-keys').checked,delay:Number($('delay').value)});$('record-dialog').close();}finally{$('start').disabled=false;$('start').textContent='● เริ่มบันทึก';}});
$('marker-mode').onclick=()=>{markerMode=!markerMode;renderMarker();};
$('image-wrap').onclick=e=>{if(!markerMode)return;const r=$('step-image').getBoundingClientRect();current().marker={x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};markerMode=false;queueUpdate();renderMarker();};
$('marker-toggle').onclick=()=>{const s=current();if(s.marker){lastMarker=s.marker;s.marker=null;}else{s.marker=lastMarker||{x:.5,y:.5};}queueUpdate();renderMarker();};
function move(delta){const a=state.project.steps,i=a.findIndex(s=>s.id===selectedId);if(i+delta<0||i+delta>=a.length)return;[a[i],a[i+delta]]=[a[i+delta],a[i]];queueUpdate();render();}
$('move-up').onclick=()=>move(-1);$('move-down').onclick=()=>move(1);
$('delete-step').onclick=()=>{$('confirm-dialog').showModal();};$('cancel-delete').onclick=()=>{$('confirm-dialog').close();};
$('confirm-delete').onclick=()=>{undoState={projectId:state.project.id,index:state.project.steps.findIndex(s=>s.id===selectedId),step:structuredClone(current())};state.project.steps=state.project.steps.filter(s=>s.id!==selectedId);$('confirm-dialog').close();queueUpdate();render();toast('ลบขั้นตอนแล้ว',false,true);};
$('undo').onclick=()=>{if(undoState && undoState.projectId===state.project.id){state.project.steps.splice(undoState.index,0,undoState.step);selectedId=undoState.step.id;undoState=null;queueUpdate();render();$('toast').hidden=true;}};
$('toast-close').onclick=()=>{$('toast').hidden=true;};
$('zoom').onclick=()=>{const copy=$('image-wrap').cloneNode(true);copy.removeAttribute('id');copy.classList.remove('marking');copy.querySelectorAll('[id]').forEach(el=>el.removeAttribute('id'));$('zoom-content').replaceChildren(copy);$('zoom-dialog').showModal();};
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();$('save').click();}});
window.stepfolio.onState(next=>{state=next;render();});window.stepfolio.onNotice(n=>toast(n.message,n.error));
(async()=>{state=await api('state');render();const mod=state.platform==='darwin'?'⌘':'Ctrl';$('shortcut').textContent=mod+' ⇧ S';$('stop-key').textContent=mod+' + Shift + S';$('capture-key').textContent=mod+' + Shift + Space';$('recovery').hidden=!(await api('hasRecovery'));})().catch(e=>toast(e.message,true));
